PORTNAME=	xlibre-vfb
PORTVERSION=	${XLIBRE_VER}
CATEGORIES=	x11-servers

MAINTAINER=	b-aazbsd@proton.me
COMMENT=	Xlibre Xvfb server
WWW=		https://github.com/xlibre/xserver

LICENSE=	MIT

CONFLICTS_INSTALL=	xorg-vfbserver

USES=		xlibre-cat:server

.include "../xlibre-server/Makefile.common"
