    COMMENT = X11 drivers

    SUBDIR += xf86-input-egalax
    SUBDIR += xf86-video-scfb
    SUBDIR += xlibre-drivers
    SUBDIR += xlibre-xf86-input-elographics
    SUBDIR += xlibre-xf86-input-evdev
    SUBDIR += xlibre-xf86-input-joystick
    SUBDIR += xlibre-xf86-input-keyboard
    SUBDIR += xlibre-xf86-input-libinput
    SUBDIR += xlibre-xf86-input-mouse
    SUBDIR += xlibre-xf86-input-synaptics
    SUBDIR += xlibre-xf86-input-vmmouse
    SUBDIR += xlibre-xf86-input-void
    SUBDIR += xlibre-xf86-input-wacom
    SUBDIR += xlibre-xf86-video-amdgpu
    SUBDIR += xlibre-xf86-video-ast
    SUBDIR += xlibre-xf86-video-ati
    SUBDIR += xlibre-xf86-video-dummy
    SUBDIR += xlibre-xf86-video-intel
    SUBDIR += xlibre-xf86-video-mga
    SUBDIR += xlibre-xf86-video-nv
    SUBDIR += xlibre-xf86-video-qxl
    SUBDIR += xlibre-xf86-video-vesa
    SUBDIR += xlibre-xf86-video-vmware
    SUBDIR += xorgxrdp
    SUBDIR += xorgxrdp-devel

.include <bsd.port.subdir.mk>
