#!/bin/sh
# ^^ this doesn't do anything really, this file is a list of commands being sent
# into the VM's interactive shell prompt as a series of key presses. The shebang
# is kept for easy syntax reignition by editors and maybe testing.
# Additionally comments are all filtered out before the script sends the
# command lines to the VM, so you don't need to worry about long comments
# bugging down the interactive shells.
ifconfig em0 up
dhclient em0
echo 'UsePAM yes' >> /etc/ssh/sshd_config
echo 'PasswordAuthentication no' >> /etc/ssh/sshd_config
echo 'KbdInteractiveAuthentication no' >>/etc/ssh/sshd_config
echo 'PubKeyAuthentication yes' >> /etc/ssh/sshd_config
echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config
mkdir ~/.ssh
echo "$HOST_KEY" > ~/.ssh/authorized_keys
echo 'sshd_enable="YES"' >> /etc/rc.conf
service sshd start
service sshd reload
exit

