on:
  push:
    branches:
      - main
      - ci-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -L $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/tarball/$GITHUB_REF | tar -xz --strip-components=1
        ls
