name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'test'
        run: |
          ls
          mount
      - uses: vmactions/dragonflybsd-vm@v1
        with:
          usesh: true
          run: |
            ./.github/script/dfbsd.sh
      - name: 'test2'
        run: |
          ls
          mount
